# Generated by Django 4.1.3 on 2023-01-04 08:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=50)),
                ('address', models.DateField(auto_now=True)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=12)),
                ('lattitude', models.DecimalField(decimal_places=8, max_digits=12)),
                ('address', models.CharField(max_length=400)),
                ('bed', models.IntegerField()),
                ('ventilator', models.IntegerField()),
                ('dialysis', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=5)),
                ('bloodgroup', models.CharField(max_length=5)),
                ('hospitalID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.hospital')),
            ],
        ),
    ]
