# Generated by Django 2.2.12 on 2023-01-07 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=12)),
                ('lattitude', models.DecimalField(decimal_places=8, max_digits=12)),
                ('address', models.CharField(max_length=400)),
                ('ICU_bed', models.PositiveIntegerField(default=0)),
                ('bed', models.PositiveIntegerField(default=0)),
                ('ventilator', models.PositiveIntegerField(default=0)),
                ('dialysis', models.PositiveIntegerField(default=0)),
                ('Anesthesia_machine', models.PositiveIntegerField(default=0)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=5)),
                ('bloodgroup', models.CharField(max_length=5)),
                ('diabetic', models.BooleanField(default=False)),
                ('blood_pressure_patient', models.BooleanField(default=False)),
                ('hospitalID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Hospital')),
            ],
        ),
    ]
