# Generated by Django 4.1.3 on 2023-01-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='Anesthesia_machine',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='ICU_bed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notification',
            name='blood_pressure_patient',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='diabetic',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='bed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='dialysis',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='ventilator',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
